management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
      namespace: ${METRICS_NAMESPACE:prod}

---
spring:
  config:
    activate:
      on-profile: local
management:
  metrics:
    tags:
      namespace: local
